C_SRC += arch/$(ARCH)/boot/early.c
C_SRC += arch/$(ARCH)/boot/early_serial.c
C_SRC += arch/$(ARCH)/boot/early_limine.c
C_SRC += arch/$(ARCH)/boot/early_isr.c
C_SRC += arch/$(ARCH)/boot/early_idt.c
C_SRC += arch/$(ARCH)/boot/early_pic.c
C_SRC += arch/$(ARCH)/boot/early_pit.c